/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AdditionSchedule: typeof import('./src/components/schedule/additionSchedule.vue')['default']
    CronDrawer: typeof import('./src/components/cron-drawer.vue')['default']
    DetailSchedule: typeof import('./src/components/schedule/detailSchedule.vue')['default']
    DirectiveForm: typeof import('./src/components/directive-group/directive-form.vue')['default']
    DirectiveGroup: typeof import('./src/components/directive-group/index.vue')['default']
    Header: typeof import('./src/layouts/Header.vue')['default']
    Layouts: typeof import('./src/layouts/index.vue')['default']
    Mqtt: typeof import('./src/components/service/mqtt.vue')['default']
    Reload: typeof import('./src/components/reload.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Settings: typeof import('./src/components/settings.vue')['default']
    Sidebar: typeof import('./src/layouts/Sidebar.vue')['default']
    SidebarItem: typeof import('./src/layouts/SidebarItem.vue')['default']
    UpdateSchedule: typeof import('./src/components/schedule/updateSchedule.vue')['default']
  }
}
