/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AdditionSchedule: typeof import('./../components/schedule/additionSchedule.vue')['default']
    CronDrawer: typeof import('./../components/cron-drawer.vue')['default']
    DetailSchedule: typeof import('./../components/schedule/detailSchedule.vue')['default']
    DirectiveForm: typeof import('./../components/directive-group/directive-form.vue')['default']
    DirectiveGroup: typeof import('./../components/directive-group/index.vue')['default']
    I18n: typeof import('./../components/I18n/index.vue')['default']
    Mqtt: typeof import('./../components/service/mqtt.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SettingsComponent: typeof import('./../components/settings-component.vue')['default']
    SvgIcon: typeof import('./../components/SvgIcon/index.vue')['default']
    UpdateSchedule: typeof import('./../components/schedule/updateSchedule.vue')['default']
  }
}
