name: Sync to Gitee
on:
  push:
    branches:
      - main # 替换为你要监听的分支名

jobs:
  sync-to-gitee:
    runs-on: ubuntu-latest
    steps:
      - name: Sync to Gitee
        uses: wearerequired/git-mirror-action@master
        env:
          # 注意在 Settings->Secrets 配置 GITEE_RSA_PRIVATE_KEY
          SSH_PRIVATE_KEY: ${{ secrets.GITEE_PRIVATE_KEY }}
        with:
          # 注意替换为你的 GitHub 源仓库地址
          source-repo: git@github.com:xing403/schedule.git
          # 注意替换为你的 Gitee 目标仓库地址
          destination-repo: git@gitee.com:xing403/schedule.git
